/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ludo;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Shreyas
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        this.mainActivity=mainActivity;
        move=new MoveLogs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        moveLogs = new javax.swing.JCheckBox();
        autoControl = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnRules = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        soundBtn = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ludo/images/icon.png")));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 35, 37));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moveLogs.setBackground(new java.awt.Color(33, 35, 37));
        moveLogs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        moveLogs.setForeground(new java.awt.Color(255, 255, 255));
        moveLogs.setText(" Show move logs");
        moveLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLogsActionPerformed(evt);
            }
        });
        jPanel1.add(moveLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        autoControl.setBackground(new java.awt.Color(33, 35, 37));
        autoControl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        autoControl.setForeground(new java.awt.Color(255, 255, 255));
        autoControl.setSelected(true);
        autoControl.setText(" Auto game control");
        autoControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoControlActionPerformed(evt);
            }
        });
        jPanel1.add(autoControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 20));

        btnCancel.setBackground(new java.awt.Color(126, 87, 194));
        btnCancel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 90, -1));

        btnSave.setBackground(new java.awt.Color(126, 87, 194));
        btnSave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 90, -1));

        btnRules.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnRules.setForeground(new java.awt.Color(255, 255, 255));
        btnRules.setText("Rules");
        btnRules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRulesMouseClicked(evt);
            }
        });
        jPanel1.add(btnRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        btnAbout.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("About");
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });
        jPanel1.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 20));

        soundBtn.setBackground(new java.awt.Color(33, 35, 37));
        soundBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        soundBtn.setForeground(new java.awt.Color(255, 255, 255));
        soundBtn.setSelected(true);
        soundBtn.setText(" Sounds");
        soundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundBtnActionPerformed(evt);
            }
        });
        jPanel1.add(soundBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ludo/images/settingsIcon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 340));

        setSize(new java.awt.Dimension(350, 344));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        FadingEffect fader = new FadingEffect();
        fader.fadeAway(this);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen()-xMouse,evt.getYOnScreen()-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        mainActivity.autoMode=autoMode;
        mainActivity.sounds=sounds;
        for (int i=0;i<4;i++) {
            mainActivity.house[i].sounds=sounds;
        }
        FadingEffect fader = new FadingEffect();
        fader.fadeAway(this);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void autoControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoControlActionPerformed
        // TODO add your handling code here:
        autoMode=autoControl.isSelected();
    }//GEN-LAST:event_autoControlActionPerformed

    private void moveLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLogsActionPerformed
        // TODO add your handling code here:
        debug=moveLogs.isSelected();
        if (debug) {
            
            mainActivity.debugMove=true;
        }
        else {
            mainActivity.debugMove=false;
        }
    }//GEN-LAST:event_moveLogsActionPerformed

    private void soundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundBtnActionPerformed
        // TODO add your handling code here:
        sounds=soundBtn.isSelected();
    }//GEN-LAST:event_soundBtnActionPerformed

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            File infoPage = new File(getClass().getResource("/ludo/Webpage/index.html").getFile());
            String path=infoPage.toString();
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+path);
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Error opening");
        }
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnRulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRulesMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            File infoPage = new File(getClass().getResource("/ludo/Webpage/index.html").getFile());
            String path=infoPage.toString();
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+path);
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Error opening");
        }
    }//GEN-LAST:event_btnRulesMouseClicked

    public void selectFrame(Test mainActivity) {
        this.mainActivity=mainActivity;
        autoMode=mainActivity.autoMode;
        autoControl.setSelected(autoMode);
        debug=mainActivity.debugMove;
        moveLogs.setSelected(debug);
        sounds=mainActivity.sounds;
        soundBtn.setSelected(sounds);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }
    
    int xMouse,yMouse;
    Test mainActivity;
    boolean autoMode;
    boolean debug;
    boolean sounds;
    MoveLogs move;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoControl;
    private javax.swing.JLabel btnAbout;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel btnRules;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox moveLogs;
    private javax.swing.JCheckBox soundBtn;
    // End of variables declaration//GEN-END:variables
}
